### ISSUE TITLE
com.butterproject:vlc-android-sdk:3.0.10

### ISSUE THREAD

**Issue by jswn0203** [masterwok/simple-vlc-player#1]
这个可以提供？

**Comment by masterwok** [comment]
I think you're asking why I'm using this package? I included it as I was having trouble compiling the libVLC libraries on my machine. I'm going to remove it once I'm able to compile libVLC. For now I'm focusing on functionality and using that as a plug. Please be aware that this project is in no way ready for use and is actively being worked on.

**Comment by masterwok** [comment]
"This can provide?" .. yep, I'm including it in the project for now as I was having trouble building libVLC. In the future, I would like to compile libVLC and include it in the project. Please note that this project is a work in progress and is not ready for use.
