### ISSUE TITLE
Failed to resolve: com.github.masterwok:simple-vlc-player:1.1.16

### ISSUE THREAD

**Issue by sudoanand** [masterwok/simple-vlc-player#4]
Version 1.1.16 is not released yet? Still it's in the README.md file

**Comment by masterwok** [comment]
Thank you for letting me know. That release contains two bug fixes so you'll want to pull it down.

Just a heads up, I'm not able to maintain this project at the moment and I haven't worked on this project in a few months. I'm seeing a few bugs/crashes in this library. The largest being that Android is killing the foreground service after about 20 minutes.

I'll create issues for the other crashes I'm seeing now.
